### PR TITLE
Use Basic connection manager instead of Pooling

### PR DESCRIPTION
**Pull request by alechenninger**
Because a new client is instantiated for each request, there is no need for a connection pool behind each client.

This will help #42 's reported performance implications

### CODE REVIEW

**Comment by jewzaam** [comment]
I don't know the client code and didn't have time to dig in.. does this change not require any additional tests?

**Comment by derek63** [comment]
@alechenninger This PR looks good and I am ready to merge the code, but it seems there are some merge conflicts.  Can you resolve those when you have the chance?

**Comment by luan-cestari** [comment]
For me it is OK to merge, I'm just unsure about the pooling change made, I understood that it is using the BasicHttpClientConnectionManager instead teh custom one (and some code were refactored), right?

**Comment by alechenninger** [comment]
Basically this makes the LightblueClient instance use a single threaded connection manager instead of a multithreaded one. The client instantiates and closes an entirely new client every single request, and prior to this PR it is starting up and spinning down a threadpool because that's what the default HttpClient does.

In the future the LightblueClient _really needs_ to have an injected HttpClient instead of newing it up itself. In my humble opinion I think this is a very fundamental design flaw. Based on the conversations I've had with @kahoali @jblashka and @derek63 we intend to make our own kind of "HttpClient" interface which can be implemented by plain old java.net or Apache's client or whatever. Until then, we can at least make the HttpClient implementation that the LightblueClient is newing-up internally not also new up a thread pool only to tear it down immediately.

**Comment by luan-cestari** [comment]
@alechenninger Cool. I will merge the changes. Could you open an issue for the feature that you mentioned (you probably have much more context than I to put on the description of the issue)? Also you mentioned injected, did you think we could use something like CDI (or Weld or Guice or etc)?

**Comment by alechenninger** [comment]
I don't mean any framework specific injection, I just mean dependency injection as the general technique of passing a class's dependencies instead of a class newing them up itself, which can be implemented with just plain Java via constructor injection (which is what I would propose in this case--consumers could wire this up with a framework if they desired.)

**Comment by alechenninger** [comment]
#42 is really about the dependency injection issue, though I did not fully recognize it when the issue was initially created. I've updated it.

**Pull request merged**
