### PR TITLE
fixes #273 - remove hard dependency on lightblue-core-hystrix

### LINKED ISSUE #273: Remove lightblue-core-hystrix as a dependency for the client
This ticket is split off from #267 from the hystrix elements.

The LightblueHystrixClient has a dependency on lightblue-core in order to use the ServoGraphiteSetup utiliy class. To resolve this issue, we either need to split the class in core into it's own library (that supports jdk7) or copy it into lightblue-client.

### PR DESCRIPTION
**Pull request by dcrissman**

### CODE REVIEW

**Comment by dcrissman** [comment]
This still fails, but actually builds further than it was before. So the fix work, but #267 needs to be resolved before the build will be totally stable again. Merge if you want or wait until everything is fixed.

**Comment by jewzaam** [comment]
jdk7 build fails.  Can a profile be setup for jdk7 that doesn't include the integration tests?

**Comment by bserdar** [comment]
Can we split this into two projects, one for 1.7 and one for 1.8, similar
to the structure we have for lightblue-rest?

**Comment by jewzaam** [comment]
How about a profile for jdk7 vs jdk8 where the difference is the modules built?  Is there a reason to bother building integration tests with jdk7?
 
http://maven.apache.org/guides/introduction/introduction-to-profiles.html#Profiles_in_POMs

**Comment by dcrissman** [comment]
Perhaps not, but again this will lock a jdk7 application at a certain
version. Probably ok, but doesn't resolve bug fixes or other updates.

**Comment by jewzaam** [comment]
It only means integration tests would run with jdk8, not jdk7.  If you want
to run them, even if your client needs jdk7, you build with jdk8.  It isn't
something used at runtime, so wouldn't that be reasonable?

**Comment by jewzaam** [comment]
And the client jar's published would be jdk7

**Comment by dcrissman** [comment]
I don't believe this conversation is actually being recorded in github. We
should move to either mojo or github.

**Comment by dcrissman** [comment]
Discussion did get logged to github, but to wrong issue. Above conversation should be on https://github.com/lightblue-platform/lightblue-client/issues/267

**Pull request merged**
