### PR TITLE
Move client functionality

### PR DESCRIPTION
**Pull request by dcrissman**
Moving lightblue-client test functionality to that module.

This PR must be merged at the same time as https://github.com/lightblue-platform/lightblue-test-utils/pull/19 because this reversed the dependency between the two modules.

This is related to https://github.com/lightblue-platform/lightblue-test-utils/issues/9

### CODE REVIEW

**Comment by dcrissman** [comment]
@paterczm what do you think about this PR?

**Comment by dcrissman** [comment]
Dropping to an in-progress state until after Ana .5

**Comment by dcrissman** [comment]
Artefacts for Ana 1.5 have been cut and is more of less out the door. Moving back into a ready for review status.

**Comment by luan-cestari** [comment]
I saw both https://github.com/lightblue-platform/lightblue-client/pull/100 and https://github.com/lightblue-platform/lightblue-test-utils/pull/19 . I strong agree about what @dcrissman mention in https://github.com/lightblue-platform/lightblue-test-utils/pull/19#issuecomment-97090999 . Let me know if someone else disagree, otherwise I will merge both PRs

**Pull request merged**
