### PR TITLE
remove MongoController from Execution

### PR DESCRIPTION
**Pull request by dcrissman**

### CODE REVIEW

**Comment by dcrissman** [comment]
@paterczm I am thinking we can just get rid of Execution.MongoController. Thoughts?

**Comment by paterczm** [comment]
It's there to emphasize that those are mongo only options, not applicable to rdbms or ldap. Why do you want to remove it?

**Comment by dcrissman** [comment]
> It's there to emphasize that those are mongo only options, not applicable to rdbms or ldap. Why do you want to remove it?

Ok, I can understand the argument that we might want different Executions for different backends. So with that in mind, then I question the add* methods that are on Execution. They would not be relevant to other backend types.

**Comment by dcrissman** [comment]
@paterczm - What if I simply rename Execution in this PR to MongoExecution? Then we just plan to create an LdapExecution or MariaDbExecution if and when they are needed?

**Comment by paterczm** [comment]
Makes sense. Let's make Execution and MongoExecution it's child.

**Comment by dcrissman** [comment]
@paterczm - Hows this?

**Pull request merged**
