### PR TITLE
remove deprecated constructor

### PR DESCRIPTION
**Pull request by dcrissman**
I see no reason to keep this deprecated constructor.

### CODE REVIEW

**Comment by jewzaam** [comment]
@jblashka can you confirm you don't use this constructor?

**Comment by jewzaam** [comment]
or @paterczm

**Comment by luan-cestari** [comment]
@dcrissman This PR need to be updated. Also, nobody confirmed if it is OK to remove the constructor yet

**Comment by dcrissman** [comment]
@luan-cestari I merged in changes from master. I am fine with letting this PR sit out here for a bit if needed.

**Comment by jblashka** [comment]
We still use this constructor. Doesn't mean we shouldn't get rid of this method though; we just need to update our code.

**Comment by jewzaam** [comment]
Is this a big change, @jblashka , could it be snuck into the next release?
@dcrissman since this isn't a backwards compatible change I recommend bumping major version, or we can just hold log as an issue and deal with later

**Comment by dcrissman** [comment]
@jewzaam I am honestly fine either way. Nothing is waiting on this change, I just thought I'd clean house. Lets park this change until a later date.

**Comment by luan-cestari** [comment]
Hi @dcrissman  . This PR seems fine for me, but it is in_progress. Let em know if you would like me to merge it.

**Comment by dcrissman** [comment]
Replaced by https://github.com/lightblue-platform/lightblue-client/pull/197. 

Closing.

**Pull request closed without merging**
